version: 1.16.{build}
image: Visual Studio 2017
build_script:
- ps: .\build.ps1
artifacts:
- path: 'bin**\*.nupkg'
deploy:
- provider: Environment
  name: nuget.org
  on:
    branch: master
    appveyor_repo_tag: true 